name: dropdownproplus
description: "A customizable dropdown overlay package for Flutter. #dropdown #dropdownproplus"
version: 0.0.1-dev.2
homepage: https://github.com/PravinKunnure/dropdownproplus
repository: https://github.com/PravinKunnure/dropdownproplus

environment:
  sdk: ">=3.10.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Uncomment and add any packages your dropdownpro uses
  # dio: ^6.0.0
  # flutter_dotenv: ^5.0.2
  # uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
# Assets can go here if your package needs them
# assets:
#   - assets/images/

